from django import forms
import os
import sqlite3
import pandas as pd

REGIONS = [
            ('Australia', 'Australia'),
('Outside Australia', 'Outside Australia'),
('New South Wales, NSW', 'New South Wales, NSW'),
('Victoria, VIC', 'Victoria, VIC'),
('Queensland, QLD', 'Queensland, QLD'),
('South Australia, SA', 'South Australia, SA'),
('Western Australia, WA', 'Western Australia, WA'),
('Tasmania, TAS', 'Tasmania, TAS'),
('Northern Territory, NT', 'Northern Territory, NT'),
('Australian Capital Territory, ACT', 'Australian Capital Territory, ACT'),
('Other Territories, OT', 'Other Territories, OT'),
('Outside Australia, OA', 'Outside Australia, OA'),
('Greater Sydney, NSW', 'Greater Sydney, NSW'),
('Rest of NSW, NSW', 'Rest of NSW, NSW'),
('No usual address, NSW', 'No usual address, NSW'),
('Migratory - Offshore - Shipping, NSW', 'Migratory - Offshore - Shipping, NSW'),
('Greater Melbourne, VIC', 'Greater Melbourne, VIC'),
('Rest of Vic., VIC', 'Rest of Vic., VIC'),
('No usual address, VIC', 'No usual address, VIC'),
('Migratory - Offshore - Shipping, VIC', 'Migratory - Offshore - Shipping, VIC'),
('Greater Brisbane, QLD', 'Greater Brisbane, QLD'),
('Rest of Qld, QLD', 'Rest of Qld, QLD'),
('No usual address, QLD', 'No usual address, QLD'),
('Migratory - Offshore - Shipping, QLD', 'Migratory - Offshore - Shipping, QLD'),
('Greater Adelaide, SA', 'Greater Adelaide, SA'),
('Rest of SA, SA', 'Rest of SA, SA'),
('No usual address, SA', 'No usual address, SA'),
('Migratory - Offshore - Shipping, SA', 'Migratory - Offshore - Shipping, SA'),
('Greater Perth, WA', 'Greater Perth, WA'),
('Rest of WA, WA', 'Rest of WA, WA'),
('No usual address, WA', 'No usual address, WA'),
('Migratory - Offshore - Shipping, WA', 'Migratory - Offshore - Shipping, WA'),
('Greater Hobart, TAS', 'Greater Hobart, TAS'),
('Rest of Tas., TAS', 'Rest of Tas., TAS'),
('No usual address, TAS', 'No usual address, TAS'),
('Migratory - Offshore - Shipping, TAS', 'Migratory - Offshore - Shipping, TAS'),
('Greater Darwin, NT', 'Greater Darwin, NT'),
('Rest of NT, NT', 'Rest of NT, NT'),
('No usual address, NT', 'No usual address, NT'),
('Migratory - Offshore - Shipping, NT', 'Migratory - Offshore - Shipping, NT'),
('Australian Capital Territory, ACT', 'Australian Capital Territory, ACT'),
('No usual address, ACT', 'No usual address, ACT'),
('Migratory - Offshore - Shipping, ACT', 'Migratory - Offshore - Shipping, ACT'),
('Other Territories, OT', 'Other Territories, OT'),
('No usual address, OT', 'No usual address, OT'),
('Migratory - Offshore - Shipping, OT', 'Migratory - Offshore - Shipping, OT'),
('Outside Australia, OA', 'Outside Australia, OA'),
('Not in any Significant Urban Area, NSW Town', 'Not in any Significant Urban Area, NSW Town'),
('Albury - Wodonga, VIC Town', 'Albury - Wodonga, VIC Town'),
('Armidale, NSW Town', 'Armidale, NSW Town'),
('Ballina, NSW Town', 'Ballina, NSW Town'),
('Batemans Bay, NSW Town', 'Batemans Bay, NSW Town'),
('Bathurst, NSW Town', 'Bathurst, NSW Town'),
('Bowral - Mittagong, NSW Town', 'Bowral - Mittagong, NSW Town'),
('Broken Hill, NSW Town', 'Broken Hill, NSW Town'),
('Byron Bay, NSW Town', 'Byron Bay, NSW Town'),
('Camden Haven, NSW Town', 'Camden Haven, NSW Town'),
('Central Coast, NSW Town', 'Central Coast, NSW Town'),
('Coffs Harbour, NSW Town', 'Coffs Harbour, NSW Town'),
('Dubbo, NSW Town', 'Dubbo, NSW Town'),
('Forster - Tuncurry, NSW Town', 'Forster - Tuncurry, NSW Town'),
('Goulburn, NSW Town', 'Goulburn, NSW Town'),
('Grafton, NSW Town', 'Grafton, NSW Town'),
('Griffith, NSW Town', 'Griffith, NSW Town'),
('Kempsey, NSW Town', 'Kempsey, NSW Town'),
('Lismore, NSW Town', 'Lismore, NSW Town'),
('Lithgow, NSW Town', 'Lithgow, NSW Town'),
('Medowie, NSW Town', 'Medowie, NSW Town'),
('Morisset - Cooranbong, NSW Town', 'Morisset - Cooranbong, NSW Town'),
('Mudgee, NSW Town', 'Mudgee, NSW Town'),
('Muswellbrook, NSW Town', 'Muswellbrook, NSW Town'),
('Nelson Bay, NSW Town', 'Nelson Bay, NSW Town'),
('Newcastle - Maitland, NSW Town', 'Newcastle - Maitland, NSW Town'),
('Nowra - Bomaderry, NSW Town', 'Nowra - Bomaderry, NSW Town'),
('Orange, NSW Town', 'Orange, NSW Town'),
('Port Macquarie, NSW Town', 'Port Macquarie, NSW Town'),
('Singleton, NSW Town', 'Singleton, NSW Town'),
('St Georges Basin - Sanctuary Point, NSW Town', 'St Georges Basin - Sanctuary Point, NSW Town'),
('Sydney, NSW Town', 'Sydney, NSW Town'),
('Tamworth, NSW Town', 'Tamworth, NSW Town'),
('Taree, NSW Town', 'Taree, NSW Town'),
('Ulladulla, NSW Town', 'Ulladulla, NSW Town'),
('Wagga Wagga, NSW Town', 'Wagga Wagga, NSW Town'),
('Wollongong, NSW Town', 'Wollongong, NSW Town'),
('Not in any Significant Urban Area, VIC Town', 'Not in any Significant Urban Area, VIC Town'),
('Bacchus Marsh, VIC Town', 'Bacchus Marsh, VIC Town'),
('Bairnsdale, VIC Town', 'Bairnsdale, VIC Town'),
('Ballarat, VIC Town', 'Ballarat, VIC Town'),
('Bendigo, VIC Town', 'Bendigo, VIC Town'),
('Castlemaine, VIC Town', 'Castlemaine, VIC Town'),
('Colac, VIC Town', 'Colac, VIC Town'),
('Echuca - Moama, NSW Town', 'Echuca - Moama, NSW Town'),
('Gisborne, VIC Town', 'Gisborne, VIC Town'),
('Horsham, VIC Town', 'Horsham, VIC Town'),
('Melbourne, VIC Town', 'Melbourne, VIC Town'),
('Mildura - Buronga, VIC Town', 'Mildura - Buronga, VIC Town'),
('Moe - Newborough, VIC Town', 'Moe - Newborough, VIC Town'),
('Portland, VIC Town', 'Portland, VIC Town'),
('Sale, VIC Town', 'Sale, VIC Town'),
('Shepparton - Mooroopna, VIC Town', 'Shepparton - Mooroopna, VIC Town'),
('Swan Hill, VIC Town', 'Swan Hill, VIC Town'),
('Traralgon - Morwell, VIC Town', 'Traralgon - Morwell, VIC Town'),
('Wangaratta, VIC Town', 'Wangaratta, VIC Town'),
('Warragul - Drouin, VIC Town', 'Warragul - Drouin, VIC Town'),
('Warrnambool, VIC Town', 'Warrnambool, VIC Town'),
('Not in any Significant Urban Area, QLD Town', 'Not in any Significant Urban Area, QLD Town'),
('Brisbane, QLD Town', 'Brisbane, QLD Town'),
('Bundaberg, QLD Town', 'Bundaberg, QLD Town'),
('Cairns, QLD Town', 'Cairns, QLD Town'),
('Emerald, QLD Town', 'Emerald, QLD Town'),
('Gladstone, QLD Town', 'Gladstone, QLD Town'),
('Gold Coast - Tweed Heads, QLD Town', 'Gold Coast - Tweed Heads, QLD Town'),
('Gympie, QLD Town', 'Gympie, QLD Town'),
('Hervey Bay, QLD Town', 'Hervey Bay, QLD Town'),
('Kingaroy, QLD Town', 'Kingaroy, QLD Town'),
('Mackay, QLD Town', 'Mackay, QLD Town'),
('Maryborough, QLD Town', 'Maryborough, QLD Town'),
('Mount Isa, QLD Town', 'Mount Isa, QLD Town'),
('Rockhampton, QLD Town', 'Rockhampton, QLD Town'),
('Sunshine Coast, QLD Town', 'Sunshine Coast, QLD Town'),
('Toowoomba, QLD Town', 'Toowoomba, QLD Town'),
('Townsville, QLD Town', 'Townsville, QLD Town'),
('Warwick, QLD Town', 'Warwick, QLD Town'),
('Yeppoon, QLD Town', 'Yeppoon, QLD Town'),
('Not in any Significant Urban Area, SA Town', 'Not in any Significant Urban Area, SA Town'),
('Adelaide, SA Town', 'Adelaide, SA Town'),
('Mount Gambier, SA Town', 'Mount Gambier, SA Town'),
('Murray Bridge, SA Town', 'Murray Bridge, SA Town'),
('Port Augusta, SA Town', 'Port Augusta, SA Town'),
('Port Lincoln, SA Town', 'Port Lincoln, SA Town'),
('Port Pirie, SA Town', 'Port Pirie, SA Town'),
('Whyalla, SA Town', 'Whyalla, SA Town'),
('Not in any Significant Urban Area, WA Town', 'Not in any Significant Urban Area, WA Town'),
('Albany, WA Town', 'Albany, WA Town'),
('Broome, WA Town', 'Broome, WA Town'),
('Bunbury, WA Town', 'Bunbury, WA Town'),
('Busselton, WA Town', 'Busselton, WA Town'),
('Esperance, WA Town', 'Esperance, WA Town'),
('Geraldton, WA Town', 'Geraldton, WA Town'),
('Kalgoorlie - Boulder, WA Town', 'Kalgoorlie - Boulder, WA Town'),
('Karratha, WA Town', 'Karratha, WA Town'),
('Perth, WA Town', 'Perth, WA Town'),
('Port Hedland, WA Town', 'Port Hedland, WA Town'),
('Not in any Significant Urban Area, TAS Town', 'Not in any Significant Urban Area, TAS Town'),
('Burnie - Somerset, TAS Town', 'Burnie - Somerset, TAS Town'),
('Devonport, TAS Town', 'Devonport, TAS Town'),
('Hobart, TAS Town', 'Hobart, TAS Town'),
('Launceston, TAS Town', 'Launceston, TAS Town'),
('Ulverstone, TAS Town', 'Ulverstone, TAS Town'),
('Not in any Significant Urban Area, NT Town', 'Not in any Significant Urban Area, NT Town'),
('Alice Springs, NT Town', 'Alice Springs, NT Town'),
('Darwin, NT Town', 'Darwin, NT Town'),
('Not in any Significant Urban Area, ACT Town', 'Not in any Significant Urban Area, ACT Town'),
('Canberra - Queanbeyan, ACT Town', 'Canberra - Queanbeyan, ACT Town'),
('Not in any Significant Urban Area, WA Town', 'Not in any Significant Urban Area, WA Town'),
('Albury, NSW LGA', 'Albury, NSW LGA'),
('Armidale Regional, NSW LGA', 'Armidale Regional, NSW LGA'),
('Ballina, NSW LGA', 'Ballina, NSW LGA'),
('Balranald, NSW LGA', 'Balranald, NSW LGA'),
('Bathurst Regional, NSW LGA', 'Bathurst Regional, NSW LGA'),
('Bayside, NSW LGA', 'Bayside, NSW LGA'),
('Bega Valley, NSW LGA', 'Bega Valley, NSW LGA'),
('Bellingen, NSW LGA', 'Bellingen, NSW LGA'),
('Berrigan, NSW LGA', 'Berrigan, NSW LGA'),
('Blacktown, NSW LGA', 'Blacktown, NSW LGA'),
('Bland, NSW LGA', 'Bland, NSW LGA'),
('Blayney, NSW LGA', 'Blayney, NSW LGA'),
('Blue Mountains, NSW LGA', 'Blue Mountains, NSW LGA'),
('Bogan, NSW LGA', 'Bogan, NSW LGA'),
('Bourke, NSW LGA', 'Bourke, NSW LGA'),
('Brewarrina, NSW LGA', 'Brewarrina, NSW LGA'),
('Broken Hill, NSW LGA', 'Broken Hill, NSW LGA'),
('Burwood, NSW LGA', 'Burwood, NSW LGA'),
('Byron, NSW LGA', 'Byron, NSW LGA'),
('Cabonne, NSW LGA', 'Cabonne, NSW LGA'),
('Camden, NSW LGA', 'Camden, NSW LGA'),
('Campbelltown, NSW LGA', 'Campbelltown, NSW LGA'),
('Canada Bay, NSW LGA', 'Canada Bay, NSW LGA'),
('Canterbury-Bankstown, NSW LGA', 'Canterbury-Bankstown, NSW LGA'),
('Carrathool, NSW LGA', 'Carrathool, NSW LGA'),
('Central Coast, NSW LGA', 'Central Coast, NSW LGA'),
('Central Darling, NSW LGA', 'Central Darling, NSW LGA'),
('Cessnock, NSW LGA', 'Cessnock, NSW LGA'),
('Clarence Valley, NSW LGA', 'Clarence Valley, NSW LGA'),
('Cobar, NSW LGA', 'Cobar, NSW LGA'),
('Coffs Harbour, NSW LGA', 'Coffs Harbour, NSW LGA'),
('Coolamon, NSW LGA', 'Coolamon, NSW LGA'),
('Coonamble, NSW LGA', 'Coonamble, NSW LGA'),
('Cootamundra-Gundagai Regional, NSW LGA', 'Cootamundra-Gundagai Regional, NSW LGA'),
('Cowra, NSW LGA', 'Cowra, NSW LGA'),
('Cumberland, NSW LGA', 'Cumberland, NSW LGA'),
('Dubbo Regional, NSW LGA', 'Dubbo Regional, NSW LGA'),
('Dungog, NSW LGA', 'Dungog, NSW LGA'),
('Edward River, NSW LGA', 'Edward River, NSW LGA'),
('Eurobodalla, NSW LGA', 'Eurobodalla, NSW LGA'),
('Fairfield, NSW LGA', 'Fairfield, NSW LGA'),
('Federation, NSW LGA', 'Federation, NSW LGA'),
('Forbes, NSW LGA', 'Forbes, NSW LGA'),
('Georges River, NSW LGA', 'Georges River, NSW LGA'),
('Gilgandra, NSW LGA', 'Gilgandra, NSW LGA'),
('Glen Innes Severn, NSW LGA', 'Glen Innes Severn, NSW LGA'),
('Goulburn Mulwaree, NSW LGA', 'Goulburn Mulwaree, NSW LGA'),
('Greater Hume Shire, NSW LGA', 'Greater Hume Shire, NSW LGA'),
('Griffith, NSW LGA', 'Griffith, NSW LGA'),
('Gunnedah, NSW LGA', 'Gunnedah, NSW LGA'),
('Gwydir, NSW LGA', 'Gwydir, NSW LGA'),
('Hawkesbury, NSW LGA', 'Hawkesbury, NSW LGA'),
('Hay, NSW LGA', 'Hay, NSW LGA'),
('Hilltops, NSW LGA', 'Hilltops, NSW LGA'),
('Hornsby, NSW LGA', 'Hornsby, NSW LGA'),
('Hunters Hill, NSW LGA', 'Hunters Hill, NSW LGA'),
('Inner West, NSW LGA', 'Inner West, NSW LGA'),
('Inverell, NSW LGA', 'Inverell, NSW LGA'),
('Junee, NSW LGA', 'Junee, NSW LGA'),
('Kempsey, NSW LGA', 'Kempsey, NSW LGA'),
('Kiama, NSW LGA', 'Kiama, NSW LGA'),
('Ku-ring-gai, NSW LGA', 'Ku-ring-gai, NSW LGA'),
('Kyogle, NSW LGA', 'Kyogle, NSW LGA'),
('Lachlan, NSW LGA', 'Lachlan, NSW LGA'),
('Lake Macquarie, NSW LGA', 'Lake Macquarie, NSW LGA'),
('Lane Cove, NSW LGA', 'Lane Cove, NSW LGA'),
('Leeton, NSW LGA', 'Leeton, NSW LGA'),
('Lismore, NSW LGA', 'Lismore, NSW LGA'),
('Lithgow, NSW LGA', 'Lithgow, NSW LGA'),
('Liverpool, NSW LGA', 'Liverpool, NSW LGA'),
('Liverpool Plains, NSW LGA', 'Liverpool Plains, NSW LGA'),
('Lockhart, NSW LGA', 'Lockhart, NSW LGA'),
('Maitland, NSW LGA', 'Maitland, NSW LGA'),
('Mid-Coast, NSW LGA', 'Mid-Coast, NSW LGA'),
('Mid-Western Regional, NSW LGA', 'Mid-Western Regional, NSW LGA'),
('Moree Plains, NSW LGA', 'Moree Plains, NSW LGA'),
('Mosman, NSW LGA', 'Mosman, NSW LGA'),
('Murray River, NSW LGA', 'Murray River, NSW LGA'),
('Murrumbidgee, NSW LGA', 'Murrumbidgee, NSW LGA'),
('Muswellbrook, NSW LGA', 'Muswellbrook, NSW LGA'),
('Nambucca Valley, NSW LGA', 'Nambucca Valley, NSW LGA'),
('Narrabri, NSW LGA', 'Narrabri, NSW LGA'),
('Narrandera, NSW LGA', 'Narrandera, NSW LGA'),
('Narromine, NSW LGA', 'Narromine, NSW LGA'),
('Newcastle, NSW LGA', 'Newcastle, NSW LGA'),
('North Sydney, NSW LGA', 'North Sydney, NSW LGA'),
('Northern Beaches, NSW LGA', 'Northern Beaches, NSW LGA'),
('Oberon, NSW LGA', 'Oberon, NSW LGA'),
('Orange, NSW LGA', 'Orange, NSW LGA'),
('Parkes, NSW LGA', 'Parkes, NSW LGA'),
('Parramatta, NSW LGA', 'Parramatta, NSW LGA'),
('Penrith, NSW LGA', 'Penrith, NSW LGA'),
('Port Macquarie-Hastings, NSW LGA', 'Port Macquarie-Hastings, NSW LGA'),
('Port Stephens, NSW LGA', 'Port Stephens, NSW LGA'),
('Queanbeyan-Palerang Regional, NSW LGA', 'Queanbeyan-Palerang Regional, NSW LGA'),
('Randwick, NSW LGA', 'Randwick, NSW LGA'),
('Richmond Valley, NSW LGA', 'Richmond Valley, NSW LGA'),
('Ryde, NSW LGA', 'Ryde, NSW LGA'),
('Shellharbour, NSW LGA', 'Shellharbour, NSW LGA'),
('Shoalhaven, NSW LGA', 'Shoalhaven, NSW LGA'),
('Singleton, NSW LGA', 'Singleton, NSW LGA'),
('Snowy Monaro Regional, NSW LGA', 'Snowy Monaro Regional, NSW LGA'),
('Snowy Valleys, NSW LGA', 'Snowy Valleys, NSW LGA'),
('Strathfield, NSW LGA', 'Strathfield, NSW LGA'),
('Sutherland Shire, NSW LGA', 'Sutherland Shire, NSW LGA'),
('Sydney, NSW LGA', 'Sydney, NSW LGA'),
('Tamworth Regional, NSW LGA', 'Tamworth Regional, NSW LGA'),
('Temora, NSW LGA', 'Temora, NSW LGA'),
('Tenterfield, NSW LGA', 'Tenterfield, NSW LGA'),
('The Hills Shire, NSW LGA', 'The Hills Shire, NSW LGA'),
('Tweed, NSW LGA', 'Tweed, NSW LGA'),
('Upper Hunter Shire, NSW LGA', 'Upper Hunter Shire, NSW LGA'),
('Upper Lachlan Shire, NSW LGA', 'Upper Lachlan Shire, NSW LGA'),
('Uralla, NSW LGA', 'Uralla, NSW LGA'),
('Wagga Wagga, NSW LGA', 'Wagga Wagga, NSW LGA'),
('Walcha, NSW LGA', 'Walcha, NSW LGA'),
('Walgett, NSW LGA', 'Walgett, NSW LGA'),
('Warren, NSW LGA', 'Warren, NSW LGA'),
('Warrumbungle Shire, NSW LGA', 'Warrumbungle Shire, NSW LGA'),
('Waverley, NSW LGA', 'Waverley, NSW LGA'),
('Weddin, NSW LGA', 'Weddin, NSW LGA'),
('Wentworth, NSW LGA', 'Wentworth, NSW LGA'),
('Willoughby, NSW LGA', 'Willoughby, NSW LGA'),
('Wingecarribee, NSW LGA', 'Wingecarribee, NSW LGA'),
('Wollondilly, NSW LGA', 'Wollondilly, NSW LGA'),
('Wollongong, NSW LGA', 'Wollongong, NSW LGA'),
('Woollahra, NSW LGA', 'Woollahra, NSW LGA'),
('Yass Valley, NSW LGA', 'Yass Valley, NSW LGA'),
('Unincorporated NSW, NSW LGA', 'Unincorporated NSW, NSW LGA'),
('No usual address, NSW LGA', 'No usual address, NSW LGA'),
('Migratory - Offshore - Shipping, NSW LGA', 'Migratory - Offshore - Shipping, NSW LGA'),
('Alpine, VIC LGA', 'Alpine, VIC LGA'),
('Ararat, VIC LGA', 'Ararat, VIC LGA'),
('Ballarat, VIC LGA', 'Ballarat, VIC LGA'),
('Banyule, VIC LGA', 'Banyule, VIC LGA'),
('Bass Coast, VIC LGA', 'Bass Coast, VIC LGA'),
('Baw Baw, VIC LGA', 'Baw Baw, VIC LGA'),
('Bayside, VIC LGA', 'Bayside, VIC LGA'),
('Benalla, VIC LGA', 'Benalla, VIC LGA'),
('Boroondara, VIC LGA', 'Boroondara, VIC LGA'),
('Brimbank, VIC LGA', 'Brimbank, VIC LGA'),
('Buloke, VIC LGA', 'Buloke, VIC LGA'),
('Campaspe, VIC LGA', 'Campaspe, VIC LGA'),
('Cardinia, VIC LGA', 'Cardinia, VIC LGA'),
('Casey, VIC LGA', 'Casey, VIC LGA'),
('Central Goldfields, VIC LGA', 'Central Goldfields, VIC LGA'),
('Colac Otway, VIC LGA', 'Colac Otway, VIC LGA'),
('Corangamite, VIC LGA', 'Corangamite, VIC LGA'),
('Darebin, VIC LGA', 'Darebin, VIC LGA'),
('East Gippsland, VIC LGA', 'East Gippsland, VIC LGA'),
('Frankston, VIC LGA', 'Frankston, VIC LGA'),
('Gannawarra, VIC LGA', 'Gannawarra, VIC LGA'),
('Glen Eira, VIC LGA', 'Glen Eira, VIC LGA'),
('Glenelg, VIC LGA', 'Glenelg, VIC LGA'),
('Golden Plains, VIC LGA', 'Golden Plains, VIC LGA'),
('Greater Bendigo, VIC LGA', 'Greater Bendigo, VIC LGA'),
('Greater Dandenong, VIC LGA', 'Greater Dandenong, VIC LGA'),
('Greater Geelong, VIC LGA', 'Greater Geelong, VIC LGA'),
('Greater Shepparton, VIC LGA', 'Greater Shepparton, VIC LGA'),
('Hepburn, VIC LGA', 'Hepburn, VIC LGA'),
('Hindmarsh, VIC LGA', 'Hindmarsh, VIC LGA'),
('Hobsons Bay, VIC LGA', 'Hobsons Bay, VIC LGA'),
('Horsham, VIC LGA', 'Horsham, VIC LGA'),
('Hume, VIC LGA', 'Hume, VIC LGA'),
('Indigo, VIC LGA', 'Indigo, VIC LGA'),
('Kingston, VIC LGA', 'Kingston, VIC LGA'),
('Knox, VIC LGA', 'Knox, VIC LGA'),
('Latrobe, VIC LGA', 'Latrobe, VIC LGA'),
('Loddon, VIC LGA', 'Loddon, VIC LGA'),
('Macedon Ranges, VIC LGA', 'Macedon Ranges, VIC LGA'),
('Manningham, VIC LGA', 'Manningham, VIC LGA'),
('Mansfield, VIC LGA', 'Mansfield, VIC LGA'),
('Maribyrnong, VIC LGA', 'Maribyrnong, VIC LGA'),
('Maroondah, VIC LGA', 'Maroondah, VIC LGA'),
('Melbourne, VIC LGA', 'Melbourne, VIC LGA'),
('Melton, VIC LGA', 'Melton, VIC LGA'),
('Mildura, VIC LGA', 'Mildura, VIC LGA'),
('Mitchell, VIC LGA', 'Mitchell, VIC LGA'),
('Moira, VIC LGA', 'Moira, VIC LGA'),
('Monash, VIC LGA', 'Monash, VIC LGA'),
('Moonee Valley, VIC LGA', 'Moonee Valley, VIC LGA'),
('Moorabool, VIC LGA', 'Moorabool, VIC LGA'),
('Moreland, VIC LGA', 'Moreland, VIC LGA'),
('Mornington Peninsula, VIC LGA', 'Mornington Peninsula, VIC LGA'),
('Mount Alexander, VIC LGA', 'Mount Alexander, VIC LGA'),
('Moyne, VIC LGA', 'Moyne, VIC LGA'),
('Murrindindi, VIC LGA', 'Murrindindi, VIC LGA'),
('Nillumbik, VIC LGA', 'Nillumbik, VIC LGA'),
('Northern Grampians, VIC LGA', 'Northern Grampians, VIC LGA'),
('Port Phillip, VIC LGA', 'Port Phillip, VIC LGA'),
('Pyrenees, VIC LGA', 'Pyrenees, VIC LGA'),
('Queenscliffe, VIC LGA', 'Queenscliffe, VIC LGA'),
('South Gippsland, VIC LGA', 'South Gippsland, VIC LGA'),
('Southern Grampians, VIC LGA', 'Southern Grampians, VIC LGA'),
('Stonnington, VIC LGA', 'Stonnington, VIC LGA'),
('Strathbogie, VIC LGA', 'Strathbogie, VIC LGA'),
('Surf Coast, VIC LGA', 'Surf Coast, VIC LGA'),
('Swan Hill, VIC LGA', 'Swan Hill, VIC LGA'),
('Towong, VIC LGA', 'Towong, VIC LGA'),
('Wangaratta, VIC LGA', 'Wangaratta, VIC LGA'),
('Warrnambool, VIC LGA', 'Warrnambool, VIC LGA'),
('Wellington, VIC LGA', 'Wellington, VIC LGA'),
('West Wimmera, VIC LGA', 'West Wimmera, VIC LGA'),
('Whitehorse, VIC LGA', 'Whitehorse, VIC LGA'),
('Whittlesea, VIC LGA', 'Whittlesea, VIC LGA'),
('Wodonga, VIC LGA', 'Wodonga, VIC LGA'),
('Wyndham, VIC LGA', 'Wyndham, VIC LGA'),
('Yarra, VIC LGA', 'Yarra, VIC LGA'),
('Yarra Ranges, VIC LGA', 'Yarra Ranges, VIC LGA'),
('Yarriambiack, VIC LGA', 'Yarriambiack, VIC LGA'),
('Unincorporated Vic, VIC LGA', 'Unincorporated Vic, VIC LGA'),
('No usual address, VIC LGA', 'No usual address, VIC LGA'),
('Migratory - Offshore - Shipping, VIC LGA', 'Migratory - Offshore - Shipping, VIC LGA'),
('Aurukun, QLD LGA', 'Aurukun, QLD LGA'),
('Balonne, QLD LGA', 'Balonne, QLD LGA'),
('Banana, QLD LGA', 'Banana, QLD LGA'),
('Barcaldine, QLD LGA', 'Barcaldine, QLD LGA'),
('Barcoo, QLD LGA', 'Barcoo, QLD LGA'),
('Blackall Tambo, QLD LGA', 'Blackall Tambo, QLD LGA'),
('Boulia, QLD LGA', 'Boulia, QLD LGA'),
('Brisbane, QLD LGA', 'Brisbane, QLD LGA'),
('Bulloo, QLD LGA', 'Bulloo, QLD LGA'),
('Bundaberg, QLD LGA', 'Bundaberg, QLD LGA'),
('Burdekin, QLD LGA', 'Burdekin, QLD LGA'),
('Burke, QLD LGA', 'Burke, QLD LGA'),
('Cairns, QLD LGA', 'Cairns, QLD LGA'),
('Carpentaria, QLD LGA', 'Carpentaria, QLD LGA'),
('Cassowary Coast, QLD LGA', 'Cassowary Coast, QLD LGA'),
('Central Highlands, QLD LGA', 'Central Highlands, QLD LGA'),
('Charters Towers, QLD LGA', 'Charters Towers, QLD LGA'),
('Cherbourg, QLD LGA', 'Cherbourg, QLD LGA'),
('Cloncurry, QLD LGA', 'Cloncurry, QLD LGA'),
('Cook, QLD LGA', 'Cook, QLD LGA'),
('Croydon, QLD LGA', 'Croydon, QLD LGA'),
('Diamantina, QLD LGA', 'Diamantina, QLD LGA'),
('Doomadgee, QLD LGA', 'Doomadgee, QLD LGA'),
('Douglas, QLD LGA', 'Douglas, QLD LGA'),
('Etheridge, QLD LGA', 'Etheridge, QLD LGA'),
('Flinders, QLD LGA', 'Flinders, QLD LGA'),
('Fraser Coast, QLD LGA', 'Fraser Coast, QLD LGA'),
('Gladstone, QLD LGA', 'Gladstone, QLD LGA'),
('Gold Coast, QLD LGA', 'Gold Coast, QLD LGA'),
('Goondiwindi, QLD LGA', 'Goondiwindi, QLD LGA'),
('Gympie, QLD LGA', 'Gympie, QLD LGA'),
('Hinchinbrook, QLD LGA', 'Hinchinbrook, QLD LGA'),
('Hope Vale, QLD LGA', 'Hope Vale, QLD LGA'),
('Ipswich, QLD LGA', 'Ipswich, QLD LGA'),
('Isaac, QLD LGA', 'Isaac, QLD LGA'),
('Kowanyama, QLD LGA', 'Kowanyama, QLD LGA'),
('Livingstone, QLD LGA', 'Livingstone, QLD LGA'),
('Lockhart River, QLD LGA', 'Lockhart River, QLD LGA'),
('Lockyer Valley, QLD LGA', 'Lockyer Valley, QLD LGA'),
('Logan, QLD LGA', 'Logan, QLD LGA'),
('Longreach, QLD LGA', 'Longreach, QLD LGA'),
('Mackay, QLD LGA', 'Mackay, QLD LGA'),
('McKinlay, QLD LGA', 'McKinlay, QLD LGA'),
('Mapoon, QLD LGA', 'Mapoon, QLD LGA'),
('Maranoa, QLD LGA', 'Maranoa, QLD LGA'),
('Mareeba, QLD LGA', 'Mareeba, QLD LGA'),
('Moreton Bay, QLD LGA', 'Moreton Bay, QLD LGA'),
('Mornington, QLD LGA', 'Mornington, QLD LGA'),
('Mount Isa, QLD LGA', 'Mount Isa, QLD LGA'),
('Murweh, QLD LGA', 'Murweh, QLD LGA'),
('Napranum, QLD LGA', 'Napranum, QLD LGA'),
('Noosa, QLD LGA', 'Noosa, QLD LGA'),
('North Burnett, QLD LGA', 'North Burnett, QLD LGA'),
('Northern Peninsula Area, QLD LGA', 'Northern Peninsula Area, QLD LGA'),
('Palm Island, QLD LGA', 'Palm Island, QLD LGA'),
('Paroo, QLD LGA', 'Paroo, QLD LGA'),
('Pormpuraaw, QLD LGA', 'Pormpuraaw, QLD LGA'),
('Quilpie, QLD LGA', 'Quilpie, QLD LGA'),
('Redland, QLD LGA', 'Redland, QLD LGA'),
('Richmond, QLD LGA', 'Richmond, QLD LGA'),
('Rockhampton, QLD LGA', 'Rockhampton, QLD LGA'),
('Scenic Rim, QLD LGA', 'Scenic Rim, QLD LGA'),
('Somerset, QLD LGA', 'Somerset, QLD LGA'),
('South Burnett, QLD LGA', 'South Burnett, QLD LGA'),
('Southern Downs, QLD LGA', 'Southern Downs, QLD LGA'),
('Sunshine Coast, QLD LGA', 'Sunshine Coast, QLD LGA'),
('Tablelands, QLD LGA', 'Tablelands, QLD LGA'),
('Toowoomba, QLD LGA', 'Toowoomba, QLD LGA'),
('Torres, QLD LGA', 'Torres, QLD LGA'),
('Torres Strait Island, QLD LGA', 'Torres Strait Island, QLD LGA'),
('Townsville, QLD LGA', 'Townsville, QLD LGA'),
('Weipa, QLD LGA', 'Weipa, QLD LGA'),
('Western Downs, QLD LGA', 'Western Downs, QLD LGA'),
('Whitsunday, QLD LGA', 'Whitsunday, QLD LGA'),
('Winton, QLD LGA', 'Winton, QLD LGA'),
('Woorabinda, QLD LGA', 'Woorabinda, QLD LGA'),
('Wujal Wujal, QLD LGA', 'Wujal Wujal, QLD LGA'),
('Yarrabah, QLD LGA', 'Yarrabah, QLD LGA'),
('No usual address, QLD LGA', 'No usual address, QLD LGA'),
('Migratory - Offshore - Shipping, QLD LGA', 'Migratory - Offshore - Shipping, QLD LGA'),
('Adelaide, SA LGA', 'Adelaide, SA LGA'),
('Adelaide Hills, SA LGA', 'Adelaide Hills, SA LGA'),
('Adelaide Plains, SA LGA', 'Adelaide Plains, SA LGA'),
('Alexandrina, SA LGA', 'Alexandrina, SA LGA'),
('Anangu Pitjantjatjara Yunkunytjatjara, SA LGA', 'Anangu Pitjantjatjara Yunkunytjatjara, SA LGA'),
('Barossa, SA LGA', 'Barossa, SA LGA'),
('Barunga West, SA LGA', 'Barunga West, SA LGA'),
('Berri Barmera, SA LGA', 'Berri Barmera, SA LGA'),
('Burnside, SA LGA', 'Burnside, SA LGA'),
('Campbelltown, SA LGA', 'Campbelltown, SA LGA'),
('Ceduna, SA LGA', 'Ceduna, SA LGA'),
('Charles Sturt, SA LGA', 'Charles Sturt, SA LGA'),
('Clare and Gilbert Valleys, SA LGA', 'Clare and Gilbert Valleys, SA LGA'),
('Cleve, SA LGA', 'Cleve, SA LGA'),
('Coober Pedy, SA LGA', 'Coober Pedy, SA LGA'),
('Copper Coast, SA LGA', 'Copper Coast, SA LGA'),
('Elliston, SA LGA', 'Elliston, SA LGA'),
('Flinders Ranges, SA LGA', 'Flinders Ranges, SA LGA'),
('Franklin Harbour, SA LGA', 'Franklin Harbour, SA LGA'),
('Gawler, SA LGA', 'Gawler, SA LGA'),
('Goyder, SA LGA', 'Goyder, SA LGA'),
('Grant, SA LGA', 'Grant, SA LGA'),
('Holdfast Bay, SA LGA', 'Holdfast Bay, SA LGA'),
('Kangaroo Island, SA LGA', 'Kangaroo Island, SA LGA'),
('Karoonda East Murray, SA LGA', 'Karoonda East Murray, SA LGA'),
('Kimba, SA LGA', 'Kimba, SA LGA'),
('Kingston, SA LGA', 'Kingston, SA LGA'),
('Light, SA LGA', 'Light, SA LGA'),
('Lower Eyre Peninsula, SA LGA', 'Lower Eyre Peninsula, SA LGA'),
('Loxton Waikerie, SA LGA', 'Loxton Waikerie, SA LGA'),
('Maralinga Tjarutja, SA LGA', 'Maralinga Tjarutja, SA LGA'),
('Marion, SA LGA', 'Marion, SA LGA'),
('Mid Murray, SA LGA', 'Mid Murray, SA LGA'),
('Mitcham, SA LGA', 'Mitcham, SA LGA'),
('Mount Barker, SA LGA', 'Mount Barker, SA LGA'),
('Mount Gambier, SA LGA', 'Mount Gambier, SA LGA'),
('Mount Remarkable, SA LGA', 'Mount Remarkable, SA LGA'),
('Murray Bridge, SA LGA', 'Murray Bridge, SA LGA'),
('Naracoorte Lucindale, SA LGA', 'Naracoorte Lucindale, SA LGA'),
('Northern Areas, SA LGA', 'Northern Areas, SA LGA'),
('Norwood Payneham and St Peters, SA LGA', 'Norwood Payneham and St Peters, SA LGA'),
('Onkaparinga, SA LGA', 'Onkaparinga, SA LGA'),
('Orroroo Carrieton, SA LGA', 'Orroroo Carrieton, SA LGA'),
('Peterborough, SA LGA', 'Peterborough, SA LGA'),
('Playford, SA LGA', 'Playford, SA LGA'),
('Port Adelaide Enfield, SA LGA', 'Port Adelaide Enfield, SA LGA'),
('Port Augusta, SA LGA', 'Port Augusta, SA LGA'),
('Port Lincoln, SA LGA', 'Port Lincoln, SA LGA'),
('Port Pirie, SA LGA', 'Port Pirie, SA LGA'),
('Prospect, SA LGA', 'Prospect, SA LGA'),
('Renmark Paringa, SA LGA', 'Renmark Paringa, SA LGA'),
('Robe, SA LGA', 'Robe, SA LGA'),
('Roxby Downs, SA LGA', 'Roxby Downs, SA LGA'),
('Salisbury, SA LGA', 'Salisbury, SA LGA'),
('Southern Mallee, SA LGA', 'Southern Mallee, SA LGA'),
('Streaky Bay, SA LGA', 'Streaky Bay, SA LGA'),
('Tatiara, SA LGA', 'Tatiara, SA LGA'),
('Tea Tree Gully, SA LGA', 'Tea Tree Gully, SA LGA'),
('Coorong, SA LGA', 'Coorong, SA LGA'),
('Tumby Bay, SA LGA', 'Tumby Bay, SA LGA'),
('Unley, SA LGA', 'Unley, SA LGA'),
('Victor Harbor, SA LGA', 'Victor Harbor, SA LGA'),
('Wakefield, SA LGA', 'Wakefield, SA LGA'),
('Walkerville, SA LGA', 'Walkerville, SA LGA'),
('Wattle Range, SA LGA', 'Wattle Range, SA LGA'),
('West Torrens, SA LGA', 'West Torrens, SA LGA'),
('Whyalla, SA LGA', 'Whyalla, SA LGA'),
('Wudinna, SA LGA', 'Wudinna, SA LGA'),
('Yankalilla, SA LGA', 'Yankalilla, SA LGA'),
('Yorke Peninsula, SA LGA', 'Yorke Peninsula, SA LGA'),
('Unincorporated SA, SA LGA', 'Unincorporated SA, SA LGA'),
('No usual address, SA LGA', 'No usual address, SA LGA'),
('Migratory - Offshore - Shipping, SA LGA', 'Migratory - Offshore - Shipping, SA LGA'),
('Albany, WA LGA', 'Albany, WA LGA'),
('Armadale, WA LGA', 'Armadale, WA LGA'),
('Ashburton, WA LGA', 'Ashburton, WA LGA'),
('Augusta Margaret River, WA LGA', 'Augusta Margaret River, WA LGA'),
('Bassendean, WA LGA', 'Bassendean, WA LGA'),
('Bayswater, WA LGA', 'Bayswater, WA LGA'),
('Belmont, WA LGA', 'Belmont, WA LGA'),
('Beverley, WA LGA', 'Beverley, WA LGA'),
('Boddington, WA LGA', 'Boddington, WA LGA'),
('Boyup Brook, WA LGA', 'Boyup Brook, WA LGA'),
('Bridgetown-Greenbushes, WA LGA', 'Bridgetown-Greenbushes, WA LGA'),
('Brookton, WA LGA', 'Brookton, WA LGA'),
('Broome, WA LGA', 'Broome, WA LGA'),
('Broomehill-Tambellup, WA LGA', 'Broomehill-Tambellup, WA LGA'),
('Bruce Rock, WA LGA', 'Bruce Rock, WA LGA'),
('Bunbury, WA LGA', 'Bunbury, WA LGA'),
('Busselton, WA LGA', 'Busselton, WA LGA'),
('Cambridge, WA LGA', 'Cambridge, WA LGA'),
('Canning, WA LGA', 'Canning, WA LGA'),
('Capel, WA LGA', 'Capel, WA LGA'),
('Carnamah, WA LGA', 'Carnamah, WA LGA'),
('Carnarvon, WA LGA', 'Carnarvon, WA LGA'),
('Chapman Valley, WA LGA', 'Chapman Valley, WA LGA'),
('Chittering, WA LGA', 'Chittering, WA LGA'),
('Christmas Island, OT LGA', 'Christmas Island, OT LGA'),
('Claremont, WA LGA', 'Claremont, WA LGA'),
('Cockburn, WA LGA', 'Cockburn, WA LGA'),
('Cocos Islands, OT LGA', 'Cocos Islands, OT LGA'),
('Collie, WA LGA', 'Collie, WA LGA'),
('Coolgardie, WA LGA', 'Coolgardie, WA LGA'),
('Coorow, WA LGA', 'Coorow, WA LGA'),
('Corrigin, WA LGA', 'Corrigin, WA LGA'),
('Cottesloe, WA LGA', 'Cottesloe, WA LGA'),
('Cranbrook, WA LGA', 'Cranbrook, WA LGA'),
('Cuballing, WA LGA', 'Cuballing, WA LGA'),
('Cue, WA LGA', 'Cue, WA LGA'),
('Cunderdin, WA LGA', 'Cunderdin, WA LGA'),
('Dalwallinu, WA LGA', 'Dalwallinu, WA LGA'),
('Dandaragan, WA LGA', 'Dandaragan, WA LGA'),
('Dardanup, WA LGA', 'Dardanup, WA LGA'),
('Denmark, WA LGA', 'Denmark, WA LGA'),
('Derby-West Kimberley, WA LGA', 'Derby-West Kimberley, WA LGA'),
('Donnybrook-Balingup, WA LGA', 'Donnybrook-Balingup, WA LGA'),
('Dowerin, WA LGA', 'Dowerin, WA LGA'),
('Dumbleyung, WA LGA', 'Dumbleyung, WA LGA'),
('Dundas, WA LGA', 'Dundas, WA LGA'),
('East Fremantle, WA LGA', 'East Fremantle, WA LGA'),
('East Pilbara, WA LGA', 'East Pilbara, WA LGA'),
('Esperance, WA LGA', 'Esperance, WA LGA'),
('Exmouth, WA LGA', 'Exmouth, WA LGA'),
('Fremantle, WA LGA', 'Fremantle, WA LGA'),
('Gingin, WA LGA', 'Gingin, WA LGA'),
('Gnowangerup, WA LGA', 'Gnowangerup, WA LGA'),
('Goomalling, WA LGA', 'Goomalling, WA LGA'),
('Gosnells, WA LGA', 'Gosnells, WA LGA'),
('Greater Geraldton, WA LGA', 'Greater Geraldton, WA LGA'),
('Halls Creek, WA LGA', 'Halls Creek, WA LGA'),
('Harvey, WA LGA', 'Harvey, WA LGA'),
('Irwin, WA LGA', 'Irwin, WA LGA'),
('Jerramungup, WA LGA', 'Jerramungup, WA LGA'),
('Joondalup, WA LGA', 'Joondalup, WA LGA'),
('Kalamunda, WA LGA', 'Kalamunda, WA LGA'),
('Kalgoorlie-Boulder, WA LGA', 'Kalgoorlie-Boulder, WA LGA'),
('Karratha, WA LGA', 'Karratha, WA LGA'),
('Katanning, WA LGA', 'Katanning, WA LGA'),
('Kellerberrin, WA LGA', 'Kellerberrin, WA LGA'),
('Kent, WA LGA', 'Kent, WA LGA'),
('Kojonup, WA LGA', 'Kojonup, WA LGA'),
('Kondinin, WA LGA', 'Kondinin, WA LGA'),
('Koorda, WA LGA', 'Koorda, WA LGA'),
('Kulin, WA LGA', 'Kulin, WA LGA'),
('Kwinana, WA LGA', 'Kwinana, WA LGA'),
('Lake Grace, WA LGA', 'Lake Grace, WA LGA'),
('Laverton, WA LGA', 'Laverton, WA LGA'),
('Leonora, WA LGA', 'Leonora, WA LGA'),
('Mandurah, WA LGA', 'Mandurah, WA LGA'),
('Manjimup, WA LGA', 'Manjimup, WA LGA'),
('Meekatharra, WA LGA', 'Meekatharra, WA LGA'),
('Melville, WA LGA', 'Melville, WA LGA'),
('Menzies, WA LGA', 'Menzies, WA LGA'),
('Merredin, WA LGA', 'Merredin, WA LGA'),
('Mingenew, WA LGA', 'Mingenew, WA LGA'),
('Moora, WA LGA', 'Moora, WA LGA'),
('Morawa, WA LGA', 'Morawa, WA LGA'),
('Mosman Park, WA LGA', 'Mosman Park, WA LGA'),
('Mount Magnet, WA LGA', 'Mount Magnet, WA LGA'),
('Mount Marshall, WA LGA', 'Mount Marshall, WA LGA'),
('Mukinbudin, WA LGA', 'Mukinbudin, WA LGA'),
('Mundaring, WA LGA', 'Mundaring, WA LGA'),
('Murchison, WA LGA', 'Murchison, WA LGA'),
('Murray, WA LGA', 'Murray, WA LGA'),
('Nannup, WA LGA', 'Nannup, WA LGA'),
('Narembeen, WA LGA', 'Narembeen, WA LGA'),
('Narrogin, WA LGA', 'Narrogin, WA LGA'),
('Nedlands, WA LGA', 'Nedlands, WA LGA'),
('Ngaanyatjarraku, WA LGA', 'Ngaanyatjarraku, WA LGA'),
('Northam, WA LGA', 'Northam, WA LGA'),
('Northampton, WA LGA', 'Northampton, WA LGA'),
('Nungarin, WA LGA', 'Nungarin, WA LGA'),
('Peppermint Grove, WA LGA', 'Peppermint Grove, WA LGA'),
('Perenjori, WA LGA', 'Perenjori, WA LGA'),
('Perth, WA LGA', 'Perth, WA LGA'),
('Pingelly, WA LGA', 'Pingelly, WA LGA'),
('Plantagenet, WA LGA', 'Plantagenet, WA LGA'),
('Port Hedland, WA LGA', 'Port Hedland, WA LGA'),
('Quairading, WA LGA', 'Quairading, WA LGA'),
('Ravensthorpe, WA LGA', 'Ravensthorpe, WA LGA'),
('Rockingham, WA LGA', 'Rockingham, WA LGA'),
('Sandstone, WA LGA', 'Sandstone, WA LGA'),
('Serpentine-Jarrahdale, WA LGA', 'Serpentine-Jarrahdale, WA LGA'),
('Shark Bay, WA LGA', 'Shark Bay, WA LGA'),
('South Perth, WA LGA', 'South Perth, WA LGA'),
('Stirling, WA LGA', 'Stirling, WA LGA'),
('Subiaco, WA LGA', 'Subiaco, WA LGA'),
('Swan, WA LGA', 'Swan, WA LGA'),
('Tammin, WA LGA', 'Tammin, WA LGA'),
('Three Springs, WA LGA', 'Three Springs, WA LGA'),
('Toodyay, WA LGA', 'Toodyay, WA LGA'),
('Trayning, WA LGA', 'Trayning, WA LGA'),
('Upper Gascoyne, WA LGA', 'Upper Gascoyne, WA LGA'),
('Victoria Park, WA LGA', 'Victoria Park, WA LGA'),
('Victoria Plains, WA LGA', 'Victoria Plains, WA LGA'),
('Vincent, WA LGA', 'Vincent, WA LGA'),
('Wagin, WA LGA', 'Wagin, WA LGA'),
('Wandering, WA LGA', 'Wandering, WA LGA'),
('Wanneroo, WA LGA', 'Wanneroo, WA LGA'),
('Waroona, WA LGA', 'Waroona, WA LGA'),
('West Arthur, WA LGA', 'West Arthur, WA LGA'),
('Westonia, WA LGA', 'Westonia, WA LGA'),
('Wickepin, WA LGA', 'Wickepin, WA LGA'),
('Williams, WA LGA', 'Williams, WA LGA'),
('Wiluna, WA LGA', 'Wiluna, WA LGA'),
('Wongan-Ballidu, WA LGA', 'Wongan-Ballidu, WA LGA'),
('Woodanilling, WA LGA', 'Woodanilling, WA LGA'),
('Wyalkatchem, WA LGA', 'Wyalkatchem, WA LGA'),
('Wyndham-East Kimberley, WA LGA', 'Wyndham-East Kimberley, WA LGA'),
('Yalgoo, WA LGA', 'Yalgoo, WA LGA'),
('Yilgarn, WA LGA', 'Yilgarn, WA LGA'),
('York, WA LGA', 'York, WA LGA'),
('No usual address, WA LGA', 'No usual address, WA LGA'),
('Migratory - Offshore - Shipping, WA LGA', 'Migratory - Offshore - Shipping, WA LGA'),
('Break O Day, TAS LGA', 'Break O Day, TAS LGA'),
('Brighton, TAS LGA', 'Brighton, TAS LGA'),
('Burnie, TAS LGA', 'Burnie, TAS LGA'),
('Central Coast, TAS LGA', 'Central Coast, TAS LGA'),
('Central Highlands, TAS LGA', 'Central Highlands, TAS LGA'),
('Circular Head, TAS LGA', 'Circular Head, TAS LGA'),
('Clarence, TAS LGA', 'Clarence, TAS LGA'),
('Derwent Valley, TAS LGA', 'Derwent Valley, TAS LGA'),
('Devonport, TAS LGA', 'Devonport, TAS LGA'),
('Dorset, TAS LGA', 'Dorset, TAS LGA'),
('Flinders, TAS LGA', 'Flinders, TAS LGA'),
('George Town, TAS LGA', 'George Town, TAS LGA'),
('Glamorgan-Spring Bay, TAS LGA', 'Glamorgan-Spring Bay, TAS LGA'),
('Glenorchy, TAS LGA', 'Glenorchy, TAS LGA'),
('Hobart, TAS LGA', 'Hobart, TAS LGA'),
('Huon Valley, TAS LGA', 'Huon Valley, TAS LGA'),
('Kentish, TAS LGA', 'Kentish, TAS LGA'),
('King Island, TAS LGA', 'King Island, TAS LGA'),
('Kingborough, TAS LGA', 'Kingborough, TAS LGA'),
('Latrobe, TAS LGA', 'Latrobe, TAS LGA'),
('Launceston, TAS LGA', 'Launceston, TAS LGA'),
('Meander Valley, TAS LGA', 'Meander Valley, TAS LGA'),
('Northern Midlands, TAS LGA', 'Northern Midlands, TAS LGA'),
('Sorell, TAS LGA', 'Sorell, TAS LGA'),
('Southern Midlands, TAS LGA', 'Southern Midlands, TAS LGA'),
('Tasman, TAS LGA', 'Tasman, TAS LGA'),
('Waratah-Wynyard, TAS LGA', 'Waratah-Wynyard, TAS LGA'),
('West Coast, TAS LGA', 'West Coast, TAS LGA'),
('West Tamar, TAS LGA', 'West Tamar, TAS LGA'),
('No usual address, TAS LGA', 'No usual address, TAS LGA'),
('Migratory - Offshore - Shipping, TAS LGA', 'Migratory - Offshore - Shipping, TAS LGA'),
('Alice Springs, NT LGA', 'Alice Springs, NT LGA'),
('Barkly, NT LGA', 'Barkly, NT LGA'),
('Belyuen, NT LGA', 'Belyuen, NT LGA'),
('Central Desert, NT LGA', 'Central Desert, NT LGA'),
('Coomalie, NT LGA', 'Coomalie, NT LGA'),
('Darwin, NT LGA', 'Darwin, NT LGA'),
('Darwin Waterfront Precinct, NT LGA', 'Darwin Waterfront Precinct, NT LGA'),
('East Arnhem, NT LGA', 'East Arnhem, NT LGA'),
('Katherine, NT LGA', 'Katherine, NT LGA'),
('Litchfield, NT LGA', 'Litchfield, NT LGA'),
('MacDonnell, NT LGA', 'MacDonnell, NT LGA'),
('Palmerston, NT LGA', 'Palmerston, NT LGA'),
('Roper Gulf, NT LGA', 'Roper Gulf, NT LGA'),
('Tiwi Islands, NT LGA', 'Tiwi Islands, NT LGA'),
('Victoria Daly, NT LGA', 'Victoria Daly, NT LGA'),
('Wagait, NT LGA', 'Wagait, NT LGA'),
('West Arnhem, NT LGA', 'West Arnhem, NT LGA'),
('West Daly, NT LGA', 'West Daly, NT LGA'),
('Unincorporated NT, NT LGA', 'Unincorporated NT, NT LGA'),
('No usual address, NT LGA', 'No usual address, NT LGA'),
('Migratory - Offshore - Shipping, NT LGA', 'Migratory - Offshore - Shipping, NT LGA'),
('Unincorporated ACT, ACT LGA', 'Unincorporated ACT, ACT LGA'),
('No usual address, ACT LGA', 'No usual address, ACT LGA'),
('Migratory - Offshore - Shipping, ACT LGA', 'Migratory - Offshore - Shipping, ACT LGA'),
('Unincorp. Other Territories, OT LGA', 'Unincorp. Other Territories, OT LGA'),
('No usual address, OT LGA', 'No usual address, OT LGA'),
('Migratory - Offshore - Shipping, OT LGA', 'Migratory - Offshore - Shipping, OT LGA'),
('Outside Australia, OA LGA', 'Outside Australia, OA LGA'),

        ]

class SearchForm(forms.Form):
    region = forms.ChoiceField(
        choices=REGIONS,
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False,
    )